<?php
/** @var Betelgeuse\Blog\Block\Comment\Listing $block */
?>

<h3 class="mt-5">Comments</h3>

<ul class="list-group list-group-flush">
    <?php foreach($block->getCommentCollection() as $comment) { ?>
        <li class="list-group-item list-group-item-light">
            <strong><?php echo $comment->getAuthor(); ?></strong>
            <span> | <?php echo $block->getFormatDate($comment->getCreatedAt()); ?></span>
            <p><?php echo $comment->getMessage(); ?></p>
        </li>
    <?php } ?>
</ul>
