<?php
namespace Betelgeuse\Blog\Controller\Adminhtml\Index;

use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Backend\App\Action\Context;
use Magento\Framework\View\Result\PageFactory;

class Index extends \Magento\Backend\App\Action implements HttpGetActionInterface {

    protected $resultPageFactory;

    public function __construct(
        Context $context,
        PageFactory $resultPageFactory
    )
    {
        parent::__construct($context);
        $this->resultPageFactory = $resultPageFactory;
    }

    public function execute()
    {
        die('Admin'); // magento2.dev/admin/blog/index/index
    }

//    public function dispatch(RequestInterface $request)
//    {
//        die('Admin 1');
////        return parent::dispatch($request); // TODO: Change the autogenerated stub
//    }
}
